stages:
    - deploy


deploy:  
    image: docker:latest
    stage: deploy
    script:
        - mkdir $DOCKER_CERT_PATH
        - echo "$CA" > $DOCKER_CERT_PATH/ca.pem
        - echo "$CLIENT_CERT" > $DOCKER_CERT_PATH/cert.pem
        - echo "$CLIENT_KEY" > $DOCKER_CERT_PATH/key.pem
        - docker-compose -f docker-compose.dev.yml stop
        - docker-compose -f docker-compose.dev.yml up -d --build
        - rm -rf $DOCKER_CERT_PATH
    only: 
    - development
